/* C code for program hexaPhasePutComplete, generated by snc from ../hexaPhasePutComplete.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 37 "../hexaPhasePutComplete.stt"
#include <string.h>
# line 38 "../hexaPhasePutComplete.stt"
#include <stdlib.h>
# line 40 "../hexaPhasePutComplete.stt"
static int getIntParam ( char *symVal, int dflt ) {
# line 42 "../hexaPhasePutComplete.stt"
int ival;
# line 43 "../hexaPhasePutComplete.stt"
char *more;
# line 45 "../hexaPhasePutComplete.stt"
if( symVal ) {
# line 46 "../hexaPhasePutComplete.stt"
ival = strtol( symVal, &more, 0 );
# line 47 "../hexaPhasePutComplete.stt"
if ( strcmp( more, "" ) ) {
# line 48 "../hexaPhasePutComplete.stt"
ival = dflt;
# line 49 "../hexaPhasePutComplete.stt"
}
# line 50 "../hexaPhasePutComplete.stt"
else if ( !symVal ) {
# line 51 "../hexaPhasePutComplete.stt"
ival = dflt;
# line 52 "../hexaPhasePutComplete.stt"
}
# line 53 "../hexaPhasePutComplete.stt"
}
# line 54 "../hexaPhasePutComplete.stt"
else {
# line 55 "../hexaPhasePutComplete.stt"
ival = dflt;
# line 56 "../hexaPhasePutComplete.stt"
}
# line 58 "../hexaPhasePutComplete.stt"
return ival;
# line 60 "../hexaPhasePutComplete.stt"
}
# line 62 "../hexaPhasePutComplete.stt"
static double getDblParam ( char *symVal, double dflt ) {
# line 64 "../hexaPhasePutComplete.stt"
double dbal;
# line 65 "../hexaPhasePutComplete.stt"
char *more;
# line 67 "../hexaPhasePutComplete.stt"
if( symVal ) {
# line 68 "../hexaPhasePutComplete.stt"
dbal = strtod( symVal, &more );
# line 69 "../hexaPhasePutComplete.stt"
if ( strcmp( more, "" ) ) {
# line 70 "../hexaPhasePutComplete.stt"
dbal = dflt;
# line 71 "../hexaPhasePutComplete.stt"
}
# line 72 "../hexaPhasePutComplete.stt"
else if ( !symVal ) {
# line 73 "../hexaPhasePutComplete.stt"
dbal = dflt;
# line 74 "../hexaPhasePutComplete.stt"
}
# line 75 "../hexaPhasePutComplete.stt"
}
# line 76 "../hexaPhasePutComplete.stt"
else {
# line 77 "../hexaPhasePutComplete.stt"
dbal = dflt;
# line 78 "../hexaPhasePutComplete.stt"
}
# line 80 "../hexaPhasePutComplete.stt"
return dbal;
# line 82 "../hexaPhasePutComplete.stt"
}
# line 88 "../hexaPhasePutComplete.stt"
static const EF_ID cbPvEvFlag = 1;

/* Variable declarations */
struct seqg_vars {
# line 84 "../hexaPhasePutComplete.stt"
	double cbPv;
# line 87 "../hexaPhasePutComplete.stt"
	int cbPvChange;
# line 91 "../hexaPhasePutComplete.stt"
	double cbPvBusy;
# line 94 "../hexaPhasePutComplete.stt"
	double ctlPv;
# line 97 "../hexaPhasePutComplete.stt"
	short mainSeqState1;
# line 101 "../hexaPhasePutComplete.stt"
	short mainSeqState2;
# line 105 "../hexaPhasePutComplete.stt"
	short mainSeqState3;
# line 109 "../hexaPhasePutComplete.stt"
	short mainSeqState4;
# line 113 "../hexaPhasePutComplete.stt"
	short mainSeqState5;
# line 117 "../hexaPhasePutComplete.stt"
	short mainSeqState6;
# line 121 "../hexaPhasePutComplete.stt"
	double speedReq5;
# line 124 "../hexaPhasePutComplete.stt"
	double speedReq6;
# line 127 "../hexaPhasePutComplete.stt"
	int dbg;
# line 128 "../hexaPhasePutComplete.stt"
	int maxDelayCount;
# line 129 "../hexaPhasePutComplete.stt"
	int maxTransitionDelay;
# line 130 "../hexaPhasePutComplete.stt"
	int maxCompleteDelay;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "ss1" ******/

/* Event function for state "init" in state set "ss1" */
static seqBool seqg_event_ss1_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "ss1" */
static void seqg_action_ss1_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 139 "../hexaPhasePutComplete.stt"
			seqg_var->dbg = 0;
# line 140 "../hexaPhasePutComplete.stt"
			seqg_var->maxTransitionDelay = getIntParam(seq_macValueGet(seqg_env, "transitionDelay"), 10);
# line 141 "../hexaPhasePutComplete.stt"
			seqg_var->maxCompleteDelay = getIntParam(seq_macValueGet(seqg_env, "completionDelay"), 900);
		}
		return;
	}
}

/****** Code for state "disconnected" in state set "ss1" ******/

/* Entry function for state "disconnected" in state set "ss1" */
static void seqg_entry_ss1_0_disconnected(SS_ID seqg_env)
{
# line 152 "../hexaPhasePutComplete.stt"
	if (seqg_var->dbg)
# line 152 "../hexaPhasePutComplete.stt"
		printf("disconnected\n");
}

/* Event function for state "disconnected" in state set "ss1" */
static seqBool seqg_event_ss1_0_disconnected(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 155 "../hexaPhasePutComplete.stt"
	if (seq_pvConnectCount(seqg_env) == seq_pvAssignCount(seqg_env))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 159 "../hexaPhasePutComplete.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "disconnected" in state set "ss1" */
static void seqg_action_ss1_0_disconnected(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 156 "../hexaPhasePutComplete.stt"
			if (seqg_var->dbg)
# line 156 "../hexaPhasePutComplete.stt"
				printf("All pvs connected\n");
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "commonInit" in state set "ss1" ******/

/* Entry function for state "commonInit" in state set "ss1" */
static void seqg_entry_ss1_0_commonInit(SS_ID seqg_env)
{
# line 169 "../hexaPhasePutComplete.stt"
	if (seqg_var->dbg)
# line 169 "../hexaPhasePutComplete.stt"
		printf("commonInit\n");
}

/* Event function for state "commonInit" in state set "ss1" */
static seqBool seqg_event_ss1_0_commonInit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "commonInit" in state set "ss1" */
static void seqg_action_ss1_0_commonInit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 175 "../hexaPhasePutComplete.stt"
			seq_efClear(seqg_env, cbPvEvFlag);
		}
		return;
	}
}

/****** Code for state "waitingForChange" in state set "ss1" ******/

/* Entry function for state "waitingForChange" in state set "ss1" */
static void seqg_entry_ss1_0_waitingForChange(SS_ID seqg_env)
{
# line 187 "../hexaPhasePutComplete.stt"
	if (seqg_var->dbg)
# line 187 "../hexaPhasePutComplete.stt"
		printf("waitingForChange\n");
# line 189 "../hexaPhasePutComplete.stt"
	seqg_var->cbPvChange = 0;
}

/* Event function for state "waitingForChange" in state set "ss1" */
static seqBool seqg_event_ss1_0_waitingForChange(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 193 "../hexaPhasePutComplete.stt"
	if (seq_pvConnectCount(seqg_env) < seq_pvAssignCount(seqg_env))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 196 "../hexaPhasePutComplete.stt"
	if (seqg_var->cbPvChange)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 205 "../hexaPhasePutComplete.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitingForChange" in state set "ss1" */
static void seqg_action_ss1_0_waitingForChange(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 198 "../hexaPhasePutComplete.stt"
			seqg_var->cbPvChange = 0;
# line 200 "../hexaPhasePutComplete.stt"
			seqg_var->ctlPv = seqg_var->cbPv;
# line 201 "../hexaPhasePutComplete.stt"
			seq_pvPutTmo(seqg_env, 2/*ctlPv*/, SYNC, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
# line 207 "../hexaPhasePutComplete.stt"
			seqg_var->cbPvChange = seq_efTestAndClear(seqg_env, cbPvEvFlag);
		}
		return;
	}
}

/****** Code for state "waitingForTransition" in state set "ss1" ******/

/* Entry function for state "waitingForTransition" in state set "ss1" */
static void seqg_entry_ss1_0_waitingForTransition(SS_ID seqg_env)
{
# line 219 "../hexaPhasePutComplete.stt"
	if (seqg_var->dbg)
# line 219 "../hexaPhasePutComplete.stt"
		printf("waitingForTransition\n");
# line 221 "../hexaPhasePutComplete.stt"
	seqg_var->maxDelayCount = seqg_var->maxTransitionDelay;
}

/* Event function for state "waitingForTransition" in state set "ss1" */
static seqBool seqg_event_ss1_0_waitingForTransition(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 225 "../hexaPhasePutComplete.stt"
	if (seq_pvConnectCount(seqg_env) < seq_pvAssignCount(seqg_env))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 229 "../hexaPhasePutComplete.stt"
	if (seqg_var->maxDelayCount <= 0)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 232 "../hexaPhasePutComplete.stt"
	if (seqg_var->cbPvChange)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 262 "../hexaPhasePutComplete.stt"
	if ((seqg_var->speedReq5 <= 0 && seqg_var->speedReq6 <= 0) && ((seqg_var->mainSeqState1 == 200) || (seqg_var->mainSeqState1 == 300) || (seqg_var->mainSeqState1 == 900)) && ((seqg_var->mainSeqState2 == 200) || (seqg_var->mainSeqState2 == 300) || (seqg_var->mainSeqState2 == 900)) && ((seqg_var->mainSeqState3 == 200) || (seqg_var->mainSeqState3 == 300) || (seqg_var->mainSeqState3 == 900)) && ((seqg_var->mainSeqState4 == 200) || (seqg_var->mainSeqState4 == 300) || (seqg_var->mainSeqState4 == 900)))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 272 "../hexaPhasePutComplete.stt"
	if ((seqg_var->speedReq5 > 0 || seqg_var->speedReq6 > 0) && ((seqg_var->mainSeqState1 == 200) || (seqg_var->mainSeqState1 == 300) || (seqg_var->mainSeqState1 == 900)) && ((seqg_var->mainSeqState2 == 200) || (seqg_var->mainSeqState2 == 300) || (seqg_var->mainSeqState2 == 900)) && ((seqg_var->mainSeqState3 == 200) || (seqg_var->mainSeqState3 == 300) || (seqg_var->mainSeqState3 == 900)) && ((seqg_var->mainSeqState4 == 200) || (seqg_var->mainSeqState4 == 300) || (seqg_var->mainSeqState4 == 900)) && ((seqg_var->mainSeqState5 == 200) || (seqg_var->mainSeqState5 == 300) || (seqg_var->mainSeqState5 == 900)) && ((seqg_var->mainSeqState6 == 200) || (seqg_var->mainSeqState6 == 300) || (seqg_var->mainSeqState6 == 900)))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 276 "../hexaPhasePutComplete.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 5;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitingForTransition" in state set "ss1" */
static void seqg_action_ss1_0_waitingForTransition(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 234 "../hexaPhasePutComplete.stt"
			seqg_var->cbPvChange = 0;
# line 236 "../hexaPhasePutComplete.stt"
			seqg_var->ctlPv = seqg_var->cbPv;
# line 237 "../hexaPhasePutComplete.stt"
			seq_pvPutTmo(seqg_env, 2/*ctlPv*/, SYNC, DEFAULT_TIMEOUT);
		}
		return;
	case 3:
		{
		}
		return;
	case 4:
		{
		}
		return;
	case 5:
		{
# line 278 "../hexaPhasePutComplete.stt"
			seqg_var->cbPvChange = seq_efTestAndClear(seqg_env, cbPvEvFlag);
# line 280 "../hexaPhasePutComplete.stt"
			seqg_var->maxDelayCount--;
		}
		return;
	}
}

/****** Code for state "waitingUntilComplete" in state set "ss1" ******/

/* Entry function for state "waitingUntilComplete" in state set "ss1" */
static void seqg_entry_ss1_0_waitingUntilComplete(SS_ID seqg_env)
{
# line 292 "../hexaPhasePutComplete.stt"
	if (seqg_var->dbg)
# line 292 "../hexaPhasePutComplete.stt"
		printf("waitingUntilComplete\n");
# line 294 "../hexaPhasePutComplete.stt"
	seqg_var->maxDelayCount = seqg_var->maxCompleteDelay;
}

/* Event function for state "waitingUntilComplete" in state set "ss1" */
static seqBool seqg_event_ss1_0_waitingUntilComplete(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 298 "../hexaPhasePutComplete.stt"
	if (seq_pvConnectCount(seqg_env) < seq_pvAssignCount(seqg_env))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 301 "../hexaPhasePutComplete.stt"
	if (seqg_var->maxDelayCount <= 0)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 304 "../hexaPhasePutComplete.stt"
	if (seqg_var->cbPvChange)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 320 "../hexaPhasePutComplete.stt"
	if ((seqg_var->speedReq5 <= 0 && seqg_var->speedReq6 <= 0) && (seqg_var->mainSeqState1 == 800) && (seqg_var->mainSeqState2 == 800) && (seqg_var->mainSeqState3 == 800) && (seqg_var->mainSeqState4 == 800))
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 330 "../hexaPhasePutComplete.stt"
	if ((seqg_var->speedReq5 > 0 || seqg_var->speedReq6 > 0) && (seqg_var->mainSeqState1 == 800) && (seqg_var->mainSeqState2 == 800) && (seqg_var->mainSeqState3 == 800) && (seqg_var->mainSeqState4 == 800) && (seqg_var->mainSeqState5 == 800) && (seqg_var->mainSeqState6 == 800))
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 334 "../hexaPhasePutComplete.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 5;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitingUntilComplete" in state set "ss1" */
static void seqg_action_ss1_0_waitingUntilComplete(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 306 "../hexaPhasePutComplete.stt"
			seqg_var->cbPvChange = 0;
# line 308 "../hexaPhasePutComplete.stt"
			seqg_var->ctlPv = seqg_var->cbPv;
# line 309 "../hexaPhasePutComplete.stt"
			seq_pvPutTmo(seqg_env, 2/*ctlPv*/, SYNC, DEFAULT_TIMEOUT);
		}
		return;
	case 3:
		{
		}
		return;
	case 4:
		{
		}
		return;
	case 5:
		{
# line 336 "../hexaPhasePutComplete.stt"
			seqg_var->cbPvChange = seq_efTestAndClear(seqg_env, cbPvEvFlag);
# line 338 "../hexaPhasePutComplete.stt"
			seqg_var->maxDelayCount--;
		}
		return;
	}
}

/****** Code for state "complete" in state set "ss1" ******/

/* Entry function for state "complete" in state set "ss1" */
static void seqg_entry_ss1_0_complete(SS_ID seqg_env)
{
# line 350 "../hexaPhasePutComplete.stt"
	if (seqg_var->dbg)
# line 350 "../hexaPhasePutComplete.stt"
		printf("complete\n");
# line 352 "../hexaPhasePutComplete.stt"
	seqg_var->cbPvBusy = 0;
# line 353 "../hexaPhasePutComplete.stt"
	seq_pvPutTmo(seqg_env, 1/*cbPvBusy*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Event function for state "complete" in state set "ss1" */
static seqBool seqg_event_ss1_0_complete(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 357 "../hexaPhasePutComplete.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "complete" in state set "ss1" */
static void seqg_action_ss1_0_complete(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "abort" in state set "ss1" ******/

/* Entry function for state "abort" in state set "ss1" */
static void seqg_entry_ss1_0_abort(SS_ID seqg_env)
{
# line 368 "../hexaPhasePutComplete.stt"
	if (seqg_var->dbg)
# line 368 "../hexaPhasePutComplete.stt"
		printf("abort\n");
# line 370 "../hexaPhasePutComplete.stt"
	seqg_var->cbPv = 0;
# line 371 "../hexaPhasePutComplete.stt"
	seq_pvPutTmo(seqg_env, 0/*cbPv*/, DEFAULT, DEFAULT_TIMEOUT);
# line 372 "../hexaPhasePutComplete.stt"
	seqg_var->cbPvBusy = 0;
# line 373 "../hexaPhasePutComplete.stt"
	seq_pvPutTmo(seqg_env, 1/*cbPvBusy*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Event function for state "abort" in state set "ss1" */
static seqBool seqg_event_ss1_0_abort(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 377 "../hexaPhasePutComplete.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "abort" in state set "ss1" */
static void seqg_action_ss1_0_abort(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{cbPv}", offsetof(struct seqg_vars, cbPv), "cbPv", P_DOUBLE, 1, 2, 1, 1, 0, 0},
	{"{cbPvBusy}", offsetof(struct seqg_vars, cbPvBusy), "cbPvBusy", P_DOUBLE, 1, 3, 0, 0, 0, 0},
	{"{ctlPv}", offsetof(struct seqg_vars, ctlPv), "ctlPv", P_DOUBLE, 1, 4, 0, 0, 0, 0},
	{"{mainSeqState1}", offsetof(struct seqg_vars, mainSeqState1), "mainSeqState1", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{mainSeqState2}", offsetof(struct seqg_vars, mainSeqState2), "mainSeqState2", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{mainSeqState3}", offsetof(struct seqg_vars, mainSeqState3), "mainSeqState3", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{mainSeqState4}", offsetof(struct seqg_vars, mainSeqState4), "mainSeqState4", P_SHORT, 1, 8, 0, 1, 0, 0},
	{"{mainSeqState5}", offsetof(struct seqg_vars, mainSeqState5), "mainSeqState5", P_SHORT, 1, 9, 0, 1, 0, 0},
	{"{mainSeqState6}", offsetof(struct seqg_vars, mainSeqState6), "mainSeqState6", P_SHORT, 1, 10, 0, 1, 0, 0},
	{"{speedReq5}", offsetof(struct seqg_vars, speedReq5), "speedReq5", P_DOUBLE, 1, 11, 0, 0, 0, 0},
	{"{speedReq6}", offsetof(struct seqg_vars, speedReq6), "speedReq6", P_DOUBLE, 1, 12, 0, 0, 0, 0},
};

/* Event masks for state set "ss1" */
static const seqMask seqg_mask_ss1_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_disconnected[] = {
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_commonInit[] = {
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_waitingForChange[] = {
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_waitingForTransition[] = {
	0x00001fe0,
};
static const seqMask seqg_mask_ss1_0_waitingUntilComplete[] = {
	0x00001fe0,
};
static const seqMask seqg_mask_ss1_0_complete[] = {
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_abort[] = {
	0x00000000,
};

/* State table for state set "ss1" */
static seqState seqg_states_ss1[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_ss1_0_init,
	/* event function */    seqg_event_ss1_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "disconnected",
	/* action function */   seqg_action_ss1_0_disconnected,
	/* event function */    seqg_event_ss1_0_disconnected,
	/* entry function */    seqg_entry_ss1_0_disconnected,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_disconnected,
	/* state options */     (0)
	},
	{
	/* state name */        "commonInit",
	/* action function */   seqg_action_ss1_0_commonInit,
	/* event function */    seqg_event_ss1_0_commonInit,
	/* entry function */    seqg_entry_ss1_0_commonInit,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_commonInit,
	/* state options */     (0)
	},
	{
	/* state name */        "waitingForChange",
	/* action function */   seqg_action_ss1_0_waitingForChange,
	/* event function */    seqg_event_ss1_0_waitingForChange,
	/* entry function */    seqg_entry_ss1_0_waitingForChange,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_waitingForChange,
	/* state options */     (0)
	},
	{
	/* state name */        "waitingForTransition",
	/* action function */   seqg_action_ss1_0_waitingForTransition,
	/* event function */    seqg_event_ss1_0_waitingForTransition,
	/* entry function */    seqg_entry_ss1_0_waitingForTransition,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_waitingForTransition,
	/* state options */     (0)
	},
	{
	/* state name */        "waitingUntilComplete",
	/* action function */   seqg_action_ss1_0_waitingUntilComplete,
	/* event function */    seqg_event_ss1_0_waitingUntilComplete,
	/* entry function */    seqg_entry_ss1_0_waitingUntilComplete,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_waitingUntilComplete,
	/* state options */     (0)
	},
	{
	/* state name */        "complete",
	/* action function */   seqg_action_ss1_0_complete,
	/* event function */    seqg_event_ss1_0_complete,
	/* entry function */    seqg_entry_ss1_0_complete,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_complete,
	/* state options */     (0)
	},
	{
	/* state name */        "abort",
	/* action function */   seqg_action_ss1_0_abort,
	/* event function */    seqg_event_ss1_0_abort,
	/* entry function */    seqg_entry_ss1_0_abort,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_abort,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "ss1",
	/* states */            seqg_states_ss1,
	/* number of states */  8
	},
};

/* Program table (global) */
seqProgram hexaPhasePutComplete = {
	/* magic number */      2002009,
	/* program name */      "hexaPhasePutComplete",
	/* channels */          seqg_chans,
	/* num. channels */     11,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  1,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void hexaPhasePutCompleteRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&hexaPhasePutComplete);
}
epicsExportRegistrar(hexaPhasePutCompleteRegistrar);
